# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: echo $GITHUB_WORKSPACE

  build:

    needs: checkout
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set GITHUB_WORKSPACE
      env:
        GITHUB_WORKSPACE: /home/runner/work/TaskSimple/TaskSimple/Angular
    - run: echo $GITHUB_WORKSPACE
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        npm build
        npm test -- --no-watch --no-progress --browsers=ChromeHeadless,FirefoxHeadless
